spring:
  application:
    name: currency-converter
  datasource:
    url: jdbc:h2:mem:app_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

    show-sql: true

#exchange api main address
exchange-rate-service-url: "https://api.exchangerate.host"

#cache-life-time in minutes
cache-life-time: 60

#metrics config
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true

server:
  error:
    whitelabel:
      enabled: false
    path: /error
